spring:
  application:
    name: posbackend
  datasource:
    url: jdbc:mysql://localhost:3306/posengine-schema?useSSL=false
    username: root
    password: rootUser@123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddlAuto: update
    showSql: true
    properties:
      hibernate:
        formatSql: true
    database: mysql

server:
  port: 8000
